# Generated by Django 2.1.2 on 2018-12-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LongTextDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_text', models.TextField(default='', verbose_name='long text')),
            ],
            options={
                'verbose_name': 'User Long Text Input',
                'verbose_name_plural': 'User Long Text Input',
                'db_table': 'user_long_input',
            },
        ),
        migrations.CreateModel(
            name='ShortTextDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.TextField(default='', verbose_name='short text')),
            ],
            options={
                'verbose_name': 'User Short Text Input',
                'verbose_name_plural': 'User Short Text Input',
                'db_table': 'user_short_input',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=40, null=True, verbose_name='ip address')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
            options={
                'verbose_name': 'User Access Information',
                'verbose_name_plural': 'User Access Information',
                'db_table': 'user_ip_info',
            },
        ),
        migrations.AddField(
            model_name='shorttextdb',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_summary.UserInfo'),
        ),
        migrations.AddField(
            model_name='longtextdb',
            name='user_ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_summary.UserInfo'),
        ),
    ]
