# Generated by Django 2.1.4 on 2018-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50, verbose_name='user name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='user email')),
                ('user_message', models.TextField(verbose_name='user message')),
            ],
            options={
                'verbose_name': 'User Feedback Info',
                'verbose_name_plural': 'User Feedback Info',
                'db_table': 'user_feedback_info',
            },
        ),
    ]
