# Generated by Django 2.1.4 on 2018-12-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_summary', '0002_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(default='', verbose_name='example result')),
            ],
            options={
                'verbose_name': 'Example Result',
                'verbose_name_plural': 'Example Result',
                'db_table': 'example_result',
            },
        ),
    ]
